platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
pod 'SDWebImage', '~> 3.7.2'
pod 'FMDB', '~> 2.5'
pod 'YAScrollSegmentControl', '~> 0.1.0'
pod 'UMengAnalytics-NO-IDFA'
pod 'UMengFeedback', '~> 2.3.3'